//  COMMISSION RATES 
export const TIERS = {
  standard: { label: "Standard",  oneTime: 10, recurring: 10, recurringMonths: 3  },
  silver:   { label: "Silver",    oneTime: 12, recurring: 12, recurringMonths: 6  },
  gold:     { label: "Gold",      oneTime: 15, recurring: 15, recurringMonths: 12 },
};

//  ALL OFFERS AFFILIATES CAN PROMOTE 
export const AFFILIATE_OFFERS = [
  //  PACKAGES 
  {
    id: "pkg-starter",
    category: "Package",
    name: "Starter Package",
    subtitle: "Get Online",
    description: "Basic website, contact form, WhatsApp integration, basic SEO setup. 1 month support.",
    priceMin: 150000,
    priceMax: 500000,
    type: "one-time",
    commissionNote: "10-15% of deal value",
    featured: false,
    color: "#1A4A8A",
  },
  {
    id: "pkg-growth",
    category: "Package",
    name: "Growth Package",
    subtitle: "Generate & Convert Leads",
    description: "Website + landing page, SEO setup, email automation, lead tracking CRM. 3 months support.",
    priceMin: 500000,
    priceMax: 1500000,
    type: "one-time + monthly",
    commissionNote: "10-15% setup + 10-15% of monthly for 3-12 months",
    featured: true,
    color: "#C9A84C",
  },
  {
    id: "pkg-enterprise",
    category: "Package",
    name: "Enterprise Package",
    subtitle: "Full Business System",
    description: "Full business system: CRM, automation, payment integration, AI chatbot, ongoing support.",
    priceMin: 1500000,
    priceMax: 5000000,
    type: "one-time + monthly",
    commissionNote: "8-15% setup + recurring commission",
    featured: false,
    color: "#0F172A",
  },
  {
    id: "pkg-flagship",
    category: "Package",
    name: "Full Business System Package",
    subtitle: "Flagship Offer",
    description: "Website, SEO, CRM, email automation, payment system, AI chatbot, analytics, ongoing support.",
    priceMin: 800000,
    priceMax: 5000000,
    type: "one-time + monthly",
    commissionNote: "8-15% of deal value",
    featured: true,
    color: "#C9A84C",
  },

  //  SERVICES 
  {
    id: "svc-website",
    category: "Service",
    name: "Website & Landing Page System",
    subtitle: "From N150,000",
    description: "Professional business website, 5-8 pages, SEO setup, mobile-responsive, contact forms.",
    priceMin: 150000,
    priceMax: 800000,
    type: "one-time",
    commissionNote: "10-15% of deal value",
    featured: false,
    color: "#1A4A8A",
  },
  {
    id: "svc-leads",
    category: "Service",
    name: "Lead Generation Landing Page",
    subtitle: "From N100,000",
    description: "High-converting landing page for paid ad campaigns with CRM integration and tracking.",
    priceMin: 100000,
    priceMax: 500000,
    type: "one-time",
    commissionNote: "10-15% of deal value",
    featured: false,
    color: "#1A6E3C",
  },
  {
    id: "svc-email",
    category: "Service",
    name: "Email & Follow-up Automation",
    subtitle: "From N100,000 + N20,000/mo",
    description: "Automated email sequences, lead follow-up, payment confirmations, missed inquiry recovery.",
    priceMin: 100000,
    priceMax: 400000,
    type: "one-time + monthly",
    commissionNote: "10-15% setup + recurring for 3-12 months",
    featured: false,
    color: "#7C3AED",
  },
  {
    id: "svc-seo",
    category: "Service",
    name: "SEO & Google Visibility",
    subtitle: "From N150,000 + N50,000/mo",
    description: "Google Business optimisation, local SEO, keyword targeting, map rankings, monthly reports.",
    priceMin: 150000,
    priceMax: 700000,
    type: "one-time + monthly",
    commissionNote: "10-15% setup + recurring for 3-12 months",
    featured: true,
    color: "#DC2626",
  },
  {
    id: "svc-crm",
    category: "Service",
    name: "CRM & Business Operations",
    subtitle: "From N300,000 + N30,000/mo",
    description: "Lead tracking, customer database, sales pipeline, staff tracking, analytics dashboard.",
    priceMin: 300000,
    priceMax: 2000000,
    type: "one-time + monthly",
    commissionNote: "10-15% setup + recurring for 3-12 months",
    featured: false,
    color: "#D97706",
  },
  {
    id: "svc-payments",
    category: "Service",
    name: "Payment & Business Infrastructure",
    subtitle: "From N100,000",
    description: "Payment links, QR codes, online checkout, subscription billing, invoice generation.",
    priceMin: 100000,
    priceMax: 600000,
    type: "one-time",
    commissionNote: "10-15% of deal value",
    featured: false,
    color: "#059669",
  },
  {
    id: "svc-ai",
    category: "Service",
    name: "AI & Automation Systems",
    subtitle: "From N250,000 + N50,000/mo",
    description: "AI chatbot, WhatsApp auto-replies, FAQ automation, customer onboarding, workflow automation.",
    priceMin: 250000,
    priceMax: 1500000,
    type: "one-time + monthly",
    commissionNote: "10-15% setup + recurring for 3-12 months",
    featured: false,
    color: "#0F172A",
  },
];

//  TIER BENEFITS 
export const TIER_BENEFITS = {
  standard: [
    "10% commission on all one-time fees",
    "10% recurring commission for 3 months",
    "Access to all marketing materials",
    "Affiliate dashboard and tracking",
    "Email support within 48 hours",
  ],
  silver: [
    "12% commission on all one-time fees",
    "12% recurring commission for 6 months",
    "Priority email support within 24 hours",
    "Co-branded marketing materials",
    "Monthly performance review",
    "Unlocked after 3 successful referrals",
  ],
  gold: [
    "15% commission on all one-time fees",
    "15% recurring commission for 12 months",
    "Dedicated account manager",
    "Custom affiliate landing page",
    "Priority phone support",
    "Early access to new services",
    "Unlocked after 8 referrals or N1M+ referred",
  ],
};

//  PAYOUT INFO 
export const PAYOUT_INFO = {
  minimumPayout: 20000,
  payoutSchedule: "Monthly -- last business day of each month",
  methods: ["Bank Transfer (all Nigerian banks)", "Paystack"],
  currency: "NGN",
  cookieDuration: 30,
};
